language: python
python:
  - '3.6'
notifications:
  email: false
before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get update
  - bash .travis/install_conda.sh
  - Rscript .travis/setup.R
install: "pip install -r requirements.txt"
script: make travis
after_script:
  - echo "Rendered notebook http://nbviewer.jupyter.org/urls/s3.amazonaws.com/pythonplotbuilds/tdhopper/pythonplot.com/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/Examples.$(git log -1 --pretty=format:'%h').ipynb"
addons:
  artifacts: true
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: pythonplot.com
    endpoint: pythonplot.com.s3-website-us-east-1.amazonaws.com
    region: us-east-1
    skip_cleanup: true
    local-dir: web
    acl: public_read
    default_text_charset: 'utf-8'
    detect_encoding: true
    on:
      branch: master
after_deploy:
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY python .travis/invalidate_cloudfront.py